package com.votrip.trip.entity;

import com.votrip.common.exception.ApiException;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Set;
import java.util.UUID;
import org.springframework.http.HttpStatus;

/**
 * A trip, per docs/02-SRS-ERD.md section 5.
 *
 * <p>{@code status} is a real Java enum ({@link TripStatus}): lifecycle transitions (FR-3.2)
 * branch on it and must reject illegal jumps, the same category as
 * {@link TripMember#getRole()}/{@link TripMember#getStatus()}. {@code tripType} stays a plain,
 * app-validated string backed only by the V2 migration's CHECK constraint - docs/04-FutureScope.md
 * section 4 flags native enum-style rigidity as expensive to change once data exists and calls
 * {@code EXPENSE.category}'s free-string approach the right precedent, and {@code trip_type} in
 * particular is expected to grow when community matching (docs/04-FutureScope.md section 2) adds
 * categories. Both columns stay VARCHAR + CHECK in the database either way; the difference is
 * only in how the Java side represents them. {@link #validatedTripType} is the app-layer half of
 * that CHECK the V2 migration comment promises.
 */
@Entity
@Table(name = "trips")
public class Trip {

    private static final Set<String> ALLOWED_TRIP_TYPES = Set.of("road_trip", "bike_trip", "mixed", "custom");

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "name", nullable = false, length = 255)
    private String name;

    @Column(name = "cover_image_url", length = 2048)
    private String coverImageUrl;

    @Column(name = "destination", length = 255)
    private String destination;

    // Reserved, no FK - ITINERARY_TEMPLATE doesn't exist yet. See V2 migration.
    @Column(name = "template_id")
    private UUID templateId;

    // Reserved, no FK - ORGANIZATION doesn't exist yet. See V2 migration. Nothing sets this yet.
    @Column(name = "organization_id")
    private UUID organizationId;

    @Column(name = "created_by", nullable = false, updatable = false)
    private UUID createdBy;

    @Column(name = "status", nullable = false, length = 20)
    private TripStatus status;

    @Column(name = "trip_type", nullable = false, length = 20)
    private String tripType;

    @Column(name = "start_date")
    private LocalDate startDate;

    @Column(name = "end_date")
    private LocalDate endDate;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    @Column(name = "invite_code", nullable = false, unique = true, length = 32)
    private String inviteCode;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected Trip() {
        // for JPA
    }

    private Trip(
            UUID id,
            String name,
            String destination,
            String coverImageUrl,
            UUID templateId,
            UUID createdBy,
            TripStatus status,
            String tripType,
            LocalDate startDate,
            LocalDate endDate,
            String currency,
            String inviteCode,
            Instant createdAt,
            Instant updatedAt) {
        this.id = id;
        this.name = name;
        this.destination = destination;
        this.coverImageUrl = coverImageUrl;
        this.templateId = templateId;
        this.createdBy = createdBy;
        this.status = status;
        this.tripType = tripType;
        this.startDate = startDate;
        this.endDate = endDate;
        this.currency = currency;
        this.inviteCode = inviteCode;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * A brand-new trip created by {@code createdBy}. {@code inviteCode} is generated by the
     * caller (see {@code TripService}), not here - collision-checking it against the unique
     * constraint needs repository access this entity deliberately doesn't have. {@code tripType}
     * defaults to "custom" when absent, matching FR-3.3's catch-all and the V2 migration's own
     * column DEFAULT - set explicitly in Java too, same reasoning as {@code User.active} in V1.
     */
    public static Trip create(
            String name,
            String destination,
            String coverImageUrl,
            LocalDate startDate,
            LocalDate endDate,
            String tripType,
            UUID templateId,
            UUID createdBy,
            String inviteCode) {
        Instant now = Instant.now();
        return new Trip(
                UUID.randomUUID(),
                name,
                destination,
                coverImageUrl,
                templateId,
                createdBy,
                TripStatus.PLANNING,
                validatedTripType(tripType),
                startDate,
                endDate,
                "INR",
                inviteCode,
                now,
                now);
    }

    /**
     * Applies a partial update. Null means "leave unchanged" - there is deliberately no way yet
     * to clear a previously-set nullable field (coverImageUrl, startDate, endDate) back to null;
     * that needs either a dedicated endpoint or an explicit clear-sentinel, not built here.
     */
    public void applyUpdate(
            String name,
            String destination,
            String coverImageUrl,
            LocalDate startDate,
            LocalDate endDate,
            String tripType) {
        if (name != null) {
            this.name = name;
        }
        if (destination != null) {
            this.destination = destination;
        }
        if (coverImageUrl != null) {
            this.coverImageUrl = coverImageUrl;
        }
        if (startDate != null) {
            this.startDate = startDate;
        }
        if (endDate != null) {
            this.endDate = endDate;
        }
        if (tripType != null) {
            this.tripType = validatedTripType(tripType);
        }
        this.updatedAt = Instant.now();
    }

    /** The caller (TripService) already generated and collision-checked the replacement code. */
    public void regenerateInviteCode(String newInviteCode) {
        this.inviteCode = newInviteCode;
        this.updatedAt = Instant.now();
    }

    private static String validatedTripType(String tripType) {
        if (tripType == null) {
            return "custom";
        }
        if (!ALLOWED_TRIP_TYPES.contains(tripType)) {
            throw new ApiException(
                    HttpStatus.BAD_REQUEST,
                    "INVALID_TRIP_TYPE",
                    "tripType must be one of " + ALLOWED_TRIP_TYPES + ".");
        }
        return tripType;
    }

    public UUID getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getCoverImageUrl() {
        return coverImageUrl;
    }

    public String getDestination() {
        return destination;
    }

    public UUID getTemplateId() {
        return templateId;
    }

    public UUID getOrganizationId() {
        return organizationId;
    }

    public UUID getCreatedBy() {
        return createdBy;
    }

    public TripStatus getStatus() {
        return status;
    }

    public String getTripType() {
        return tripType;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public String getCurrency() {
        return currency;
    }

    public String getInviteCode() {
        return inviteCode;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
